---
title: "Primary_outcomes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Primary_outcomes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figs/",
  fig.height = 6,
  fig.width = 8,
  fig.align = "center",
  warning=FALSE
)
```

## Load data

```{r load}
library(librarian)
librarian::shelf(here, readxl, metafor, dex, quiet = TRUE)

dat <- read_excel(here("data", "Dex_metan.xlsx"),
                  range = "B3:T11",
                  col_names=c("study", "n1i", "n2i",
                              "ai_atel", "bi_atel", "ci_atel", "di_atel",
                              "ai_pneu", "bi_pneu", "ci_pneu", "di_pneu",
                              "ai_hypo", "bi_hypo", "ci_hypo", "di_hypo",
                              "ai_ards", "bi_ards", "ci_ards", "di_ards")
                  )
print(dat, width=Inf)
```
Removed final row, containing no data (for Lee et al.)

## Main Analysis
### Atelectasis

```{r atelectasis}
dat.atelectasis <- escalc(measure="OR",
                          ai=ai_atel,
                          bi=bi_atel,
                          ci=ci_atel,
                          di=di_atel,
                          data=dat,
                          slab = study)
pm.atelectasis <- rma(yi, vi, data=dat.atelectasis, method="PM")
forest(pm.atelectasis,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))
```

### Pneumonia
```{r pneumonia}
dat.pneumonia <- escalc(measure="OR",
                          ai=ai_pneu,
                          bi=bi_pneu,
                          ci=ci_pneu,
                          di=di_pneu,
                          data=dat,
                          slab = study)

pm.pneumonia <- rma(yi, vi, data=dat.pneumonia, method="PM")
forest(pm.pneumonia,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))
```

### Hypoxemia
```{r hypoxemia}
dat.hypoxemia <- escalc(measure="OR",
                        ai=ai_hypo,
                        bi=bi_hypo,
                        ci=ci_hypo,
                        di=di_hypo,
                        data=dat,
                        slab = study)

pm.hypoxemia <- rma(yi, vi, data=dat.hypoxemia, method="PM")
forest(pm.hypoxemia,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))
```

### ARDS
```{r ARDS}
dat.ards <- escalc(measure="OR",
                        ai=ai_ards,
                        bi=bi_ards,
                        ci=ci_ards,
                        di=di_ards,
                        data=dat,
                        slab = study)

pm.ards <- rma(yi, vi, data=dat.ards, method="PM")
forest(pm.ards,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))
```
Note: n=3 here, but n=2 in forest plot in PDF. Which is correct?


## Sensitivity Analysis
HKSJ correction results in narrower CIs (plots not shown):
```{r sensitivity, eval=FALSE}
pmhk.atelectasis <- rma(yi, vi, data=dat.atelectasis, method="PM", test="knha")
forest(pmhk.atelectasis,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))

pmhk.pneumonia <- rma(yi, vi, data=dat.pneumonia, method="PM", test="knha")
forest(pmhk.pneumonia,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))

pmhk.hypoxemia <- rma(yi, vi, data=dat.hypoxemia, method="PM", test="knha")
forest(pmhk.hypoxemia,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))

pmhk.ards <- rma(yi, vi, data=dat.ards, method="PM", test="knha")
forest(pmhk.ards,
       atransf=exp,
       at=log(c(0.002, 0.01, 0.03, 0.1, 0.4, 2, 5, 10)))
```


## Funnel plots
```{r funnels}
# Atelectasis:
### carry out trim-and-fill analysis
taf.atelectasis <- trimfill(pm.atelectasis)
### draw funnel plot with missing studies filled in
funnel(taf.atelectasis, legend=TRUE)

# Pneumonia
taf.pneumonia <- trimfill(pm.pneumonia)
funnel(taf.pneumonia, legend=TRUE)
```

