---
title: "Secondary_outcomes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Secondary_outcomes}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figs/",
  fig.height = 6,
  fig.width = 8,
  fig.align = "center",
  warning=FALSE
)
```


## Load data
```{r load}
#library(librarian)
#librarian::shelf(here, readxl, metafor, quiet = TRUE)

dat.second <- readxl::read_excel(here::here("data", "Dex_metan.xlsx"),
                         range = "B17:K79",
                         col_names = c("study",
                                       "m1i", "sd1i",
                                       "m2i", "sd2i",
                                       "n1i", "n2i",
                                       "summary1", "summary2",
                                       "outcome")
                         )
```

## Secondary Outcome Analysis
### Plateau pressure
```{r plateau}
dat.plat <- metafor::escalc(measure="MD", 
                   m1i=m1i,
                   sd1i=sd1i,
                   n1i=n1i,
                   m2i=m2i,
                   sd2i=sd2i,
                   n2i=n2i,
                   data=dplyr::filter(dat.second, outcome=="Plateau Pressure"),
                   slab = study)

pm.plat <- metafor::rma(yi, vi, data=dat.plat, method="PM")
metafor::forest(pm.plat,
       at=seq(from=-8, to =2, by=2))
```

### Peak pressure
```{r peak}
dat.peak <- metafor::escalc(measure="MD",
                   m1i=m1i,
                   sd1i=sd1i,
                   n1i=n1i,
                   m2i=m2i,
                   sd2i=sd2i,
                   n2i=n2i,
                   data=dplyr::filter(dat.second, outcome=="Peak Pressure"),
                   slab = study)

pm.peak <- metafor::rma(yi, vi, data=dat.peak, method="PM")
metafor::forest(pm.peak,
       at=seq(from=-8, to =2, by=2))
```

### Respiratory Compliance:
```{r compliance}
dat.resp <- metafor::escalc(measure="MD",
                   m1i=m1i,
                   sd1i=sd1i,
                   n1i=n1i,
                   m2i=m2i,
                   sd2i=sd2i,
                   n2i=n2i,
                   data=dplyr::filter(dat.second, outcome=="Respiratory Compliance"),
                   slab = study)

pm.resp <- metafor::rma(yi, vi, data=dat.resp, method="PM")
metafor::forest(pm.resp,
       at=seq(from=0, to =8, by=2))
```

### FEV1

```{r fev1}
dat.fev1<- metafor::escalc(measure="MD",
                   m1i=m1i,
                   sd1i=sd1i,
                   n1i=n1i,
                   m2i=m2i,
                   sd2i=sd2i,
                   n2i=n2i,
                   data=dat.second[grep(pattern = "FEV1", x = dat.second$outcome), ],
                   slab = study)

pm.fev1 <- metafor::rma(yi, vi, data=dat.fev1, method="PM")
metafor::forest(pm.fev1)
```


### POD 1
```{r pod1}
dat.pod1<- metafor::escalc(measure="MD",
                   m1i=m1i,
                   sd1i=sd1i,
                   n1i=n1i,
                   m2i=m2i,
                   sd2i=sd2i,
                   n2i=n2i,
                   data=dplyr::filter(dat.second, outcome=="FEV1 POD 1"),
                   slab = study)

pm.pod1 <- metafor::rma(yi, vi, data=dat.pod1, method="PM")
metafor::forest(pm.pod1)
```

### POD 2
```{r pod2}
dat.pod2<- metafor::escalc(measure="MD",
                  m1i=m1i,
                  sd1i=sd1i,
                  n1i=n1i,
                  m2i=m2i,
                  sd2i=sd2i,
                  n2i=n2i,
                  data=dplyr::filter(dat.second, outcome=="FEV1 POD 2"),
                  slab = study)
dat.pod2
pm.pod2 <- metafor::rma(yi, vi, data=dat.pod2, method="PM")
weights(pm.pod2)
dat.pod2
metafor::forest(pm.pod2)
```

### Length of Stay
```{r LOS}
dat.los <- metafor::escalc(measure="MD",
                  m1i=m1i,
                  sd1i=sd1i,
                  n1i=n1i,
                  m2i=m2i,
                  sd2i=sd2i,
                  n2i=n2i,
                  data=dplyr::filter(dat.second, outcome=="LOS"),
                  slab = study)

pm.los <- metafor::rma(yi, vi, data=dat.los, method="PM")
dat.los
metafor::forest(pm.los)
```

Excluding outlier Jannu et al.:

```{r los exc. Jannu}
pm.los.exc.jannu <- metafor::leave1out(pm.los)
metafor::forest(pm.los.exc.jannu$estimate, sei=pm.los.exc.jannu$se, header=TRUE, xlab="Leave One Out Estimate", refline=coef(pm.los))
```

Note in the above figure that Study 4 is Jannu et al., hence this row gives the summary estimate when Jannu et al. is excluded.
